// This file is @generated by prost-build.
/// 20-byte EVM-compatible address. Mirror of sentrix-primitives::Address.
/// Wire = bytes (NOT hex string) for binary efficiency.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    /// exactly 20 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// 32-byte hash — block hash, tx hash, state root.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hash {
    /// exactly 32 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// Native amount — sentri (10^-8 SRX). u64 wire to match Sentrix internal.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Amount {
    #[prost(uint64, tag = "1")]
    pub sentri: u64,
}
/// Block height — u64 starting at 0 (genesis).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockHeight {
    #[prost(uint64, tag = "1")]
    pub value: u64,
}
/// Mirror of sentrix-primitives::Transaction. Identical wire format to chain
/// MDBX serialisation (modulo prost-encoding). Field numbers match the
/// canonical struct order; do NOT renumber on changes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Transaction {
    #[prost(message, optional, tag = "1")]
    pub txid: ::core::option::Option<Hash>,
    #[prost(message, optional, tag = "2")]
    pub from_address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "3")]
    pub to_address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "4")]
    pub amount: ::core::option::Option<Amount>,
    #[prost(message, optional, tag = "5")]
    pub fee: ::core::option::Option<Amount>,
    #[prost(uint64, tag = "6")]
    pub nonce: u64,
    #[prost(uint64, tag = "7")]
    pub timestamp: u64,
    /// 64-byte ed25519 OR 65-byte secp256k1
    #[prost(bytes = "vec", tag = "8")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// contract calldata (EVM) or staking-op blob
    #[prost(bytes = "vec", tag = "9")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "10")]
    pub chain_id: u32,
    /// 0 = transfer, 1 = contract, 2 = staking-op
    #[prost(uint32, tag = "11")]
    pub tx_type: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag = "1")]
    pub index: u64,
    #[prost(message, optional, tag = "2")]
    pub hash: ::core::option::Option<Hash>,
    #[prost(message, optional, tag = "3")]
    pub parent_hash: ::core::option::Option<Hash>,
    #[prost(message, optional, tag = "4")]
    pub state_root: ::core::option::Option<Hash>,
    #[prost(uint64, tag = "5")]
    pub timestamp: u64,
    #[prost(message, optional, tag = "6")]
    pub proposer: ::core::option::Option<Address>,
    #[prost(uint32, tag = "7")]
    pub round: u32,
    #[prost(message, repeated, tag = "8")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    /// BFT justification carried from validator-side; included for audit.
    /// Empty for blocks at h\<100_000 (pre state-root-fork).
    #[prost(bytes = "vec", tag = "9")]
    pub justification: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Account {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "2")]
    pub balance: ::core::option::Option<Amount>,
    #[prost(uint64, tag = "3")]
    pub nonce: u64,
    /// For contract accounts: 32-byte storage root + non-empty code_hash.
    #[prost(message, optional, tag = "4")]
    pub storage_root: ::core::option::Option<Hash>,
    #[prost(message, optional, tag = "5")]
    pub code_hash: ::core::option::Option<Hash>,
}
/// Server-streaming event types.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainEvent {
    /// monotonic across all events on this stream
    #[prost(uint64, tag = "100")]
    pub sequence: u64,
    /// server-wall-clock unix seconds
    #[prost(uint64, tag = "101")]
    pub timestamp: u64,
    #[prost(oneof = "chain_event::Event", tags = "1, 2, 3, 4, 5")]
    pub event: ::core::option::Option<chain_event::Event>,
}
/// Nested message and enum types in `ChainEvent`.
pub mod chain_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        BlockFinalized(super::BlockFinalized),
        #[prost(message, tag = "2")]
        PendingTx(super::PendingTx),
        #[prost(message, tag = "3")]
        ValidatorSetChange(super::ValidatorSetChange),
        #[prost(message, tag = "4")]
        Log(super::LogEmitted),
        /// Synthetic Lagged sentinel — emitted when the per-subscriber broadcast
        /// channel drops oldest events (slow consumer). Mirrors tokio broadcast
        /// RecvError::Lagged semantics. Consumer should resync state from RPC.
        #[prost(message, tag = "5")]
        Lagged(super::StreamLagged),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockFinalized {
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<Block>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PendingTx {
    #[prost(message, optional, tag = "1")]
    pub tx: ::core::option::Option<Transaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorSetChange {
    #[prost(uint32, tag = "1")]
    pub epoch: u32,
    #[prost(message, repeated, tag = "2")]
    pub active: ::prost::alloc::vec::Vec<Address>,
    #[prost(message, repeated, tag = "3")]
    pub jailed: ::prost::alloc::vec::Vec<Address>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEmitted {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<Address>,
    /// 0..4 topics per EVM convention
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<Hash>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub tx_hash: ::core::option::Option<Hash>,
    #[prost(uint64, tag = "5")]
    pub block_height: u64,
    #[prost(uint32, tag = "6")]
    pub log_index: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamLagged {
    /// events dropped since last delivery
    #[prost(uint64, tag = "1")]
    pub skipped_count: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BroadcastTxRequest {
    #[prost(message, optional, tag = "1")]
    pub tx: ::core::option::Option<Transaction>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BroadcastTxResponse {
    #[prost(message, optional, tag = "1")]
    pub txid: ::core::option::Option<Hash>,
    /// 0-indexed; FIFO ordering UX
    #[prost(uint64, tag = "2")]
    pub mempool_position: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBlockRequest {
    #[prost(oneof = "get_block_request::Selector", tags = "1, 2, 3, 4")]
    pub selector: ::core::option::Option<get_block_request::Selector>,
}
/// Nested message and enum types in `GetBlockRequest`.
pub mod get_block_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Selector {
        #[prost(message, tag = "1")]
        Height(super::BlockHeight),
        #[prost(message, tag = "2")]
        Hash(super::Hash),
        /// selector == "latest" shorthand
        #[prost(bool, tag = "3")]
        Latest(bool),
        /// selector == "finalized" (BFT-finalized head)
        #[prost(bool, tag = "4")]
        Finalized(bool),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBalanceRequest {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    /// Snapshot height — read state as-of this block. Default = latest.
    /// Returns FAILED_PRECONDITION if outside chain window.
    #[prost(message, optional, tag = "2")]
    pub at_height: ::core::option::Option<BlockHeight>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamEventsRequest {
    /// Filter set — empty = subscribe to all event types. Backend filters
    /// server-side so the wire only carries matched events.
    #[prost(enumeration = "EventFilter", repeated, tag = "1")]
    pub filters: ::prost::alloc::vec::Vec<i32>,
    /// Resume from a sequence number (0 = current head). Backend keeps last
    /// 4096 events in a ring buffer — beyond that, sequence is not resumable
    /// and the server returns FAILED_PRECONDITION.
    #[prost(uint64, tag = "2")]
    pub from_sequence: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetValidatorSetRequest {
    /// Reserved for at_height historical reads — gated on MDBX snapshot
    /// isolation (Refactor 5). v0.4 returns the latest finalized set.
    #[prost(message, optional, tag = "1")]
    pub at_height: ::core::option::Option<BlockHeight>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorSet {
    #[prost(uint32, tag = "1")]
    pub epoch: u32,
    #[prost(uint32, tag = "2")]
    pub active_count: u32,
    #[prost(uint32, tag = "3")]
    pub total_count: u32,
    /// Total stake across the active set, in sentri (10^-8 SRX).
    #[prost(uint64, tag = "4")]
    pub total_active_stake_sentri: u64,
    #[prost(message, repeated, tag = "5")]
    pub validators: ::prost::alloc::vec::Vec<ValidatorEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidatorEntry {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    #[prost(uint64, tag = "2")]
    pub stake_sentri: u64,
    #[prost(bool, tag = "3")]
    pub active: bool,
    #[prost(bool, tag = "4")]
    pub jailed: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSupplyRequest {
    #[prost(message, optional, tag = "1")]
    pub at_height: ::core::option::Option<BlockHeight>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Supply {
    /// sentri = 10^-8 SRX. Cap is fork-gated (210M pre-fork, 315M post-
    /// tokenomics-v2 at h=640800); leave conversion to display layer.
    #[prost(uint64, tag = "1")]
    pub minted_sentri: u64,
    #[prost(uint64, tag = "2")]
    pub burned_sentri: u64,
    /// = minted − burned
    #[prost(uint64, tag = "3")]
    pub circulating_sentri: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMempoolRequest {
    /// Cap returned tx headers; default 100, max 500. Larger windows need
    /// pagination (deferred). 0 = use server default (100).
    #[prost(uint32, tag = "1")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mempool {
    /// Authoritative pending-tx count. `entries` is capped by `limit`;
    /// size always reflects the full mempool depth.
    #[prost(uint32, tag = "1")]
    pub size: u32,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<MempoolEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MempoolEntry {
    #[prost(message, optional, tag = "1")]
    pub txid: ::core::option::Option<Hash>,
    #[prost(message, optional, tag = "2")]
    pub from_address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "3")]
    pub to_address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "4")]
    pub amount: ::core::option::Option<Amount>,
    #[prost(message, optional, tag = "5")]
    pub fee: ::core::option::Option<Amount>,
    #[prost(uint64, tag = "6")]
    pub nonce: u64,
    #[prost(uint32, tag = "7")]
    pub tx_type: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventFilter {
    Unspecified = 0,
    BlockFinalized = 1,
    PendingTx = 2,
    ValidatorSet = 3,
    Log = 4,
}
impl EventFilter {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EVENT_FILTER_UNSPECIFIED",
            Self::BlockFinalized => "EVENT_FILTER_BLOCK_FINALIZED",
            Self::PendingTx => "EVENT_FILTER_PENDING_TX",
            Self::ValidatorSet => "EVENT_FILTER_VALIDATOR_SET",
            Self::Log => "EVENT_FILTER_LOG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVENT_FILTER_UNSPECIFIED" => Some(Self::Unspecified),
            "EVENT_FILTER_BLOCK_FINALIZED" => Some(Self::BlockFinalized),
            "EVENT_FILTER_PENDING_TX" => Some(Self::PendingTx),
            "EVENT_FILTER_VALIDATOR_SET" => Some(Self::ValidatorSet),
            "EVENT_FILTER_LOG" => Some(Self::Log),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod sentrix_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ────────────────────────────────────────────────────────────
    /// Service definition
    /// ────────────────────────────────────────────────────────────
    #[derive(Debug, Clone)]
    pub struct SentrixClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SentrixClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SentrixClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SentrixClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SentrixClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Submit a signed transaction to the local mempool. Same semantics as
        /// JSON-RPC eth_sendRawTransaction for EVM txs, with native fields exposed
        /// for staking-ops and other native variants.
        pub async fn broadcast_tx(
            &mut self,
            request: impl tonic::IntoRequest<super::BroadcastTxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BroadcastTxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/BroadcastTx",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "BroadcastTx"));
            self.inner.unary(req, path, codec).await
        }
        /// Fetch a block by height OR by hash. Returns NOT_FOUND if outside the
        /// local chain window (currently 1000 blocks; older blocks need indexer).
        pub async fn get_block(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBlockRequest>,
        ) -> std::result::Result<tonic::Response<super::Block>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/GetBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "GetBlock"));
            self.inner.unary(req, path, codec).await
        }
        /// Fetch account balance + nonce. Mirrors eth_getBalance +
        /// eth_getTransactionCount in a single round-trip. Includes mempool-pending
        /// nonce so wallets build correct next-tx without an extra call (matches
        /// the pending-aware nonce behaviour from chain v2.1.57).
        pub async fn get_balance(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBalanceRequest>,
        ) -> std::result::Result<tonic::Response<super::Account>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/GetBalance",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "GetBalance"));
            self.inner.unary(req, path, codec).await
        }
        /// v0.4 read-only state queries — drop the REST `/sentrix_status_extended`
        /// bridge from the explorer's stats hot path. All three are pure reads
        /// off `state.read()` snapshots; same lock contention profile as
        /// GetBlock/GetBalance.
        ///
        /// Active validator set + per-validator stake/active/jailed flags.
        pub async fn get_validator_set(
            &mut self,
            request: impl tonic::IntoRequest<super::GetValidatorSetRequest>,
        ) -> std::result::Result<tonic::Response<super::ValidatorSet>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/GetValidatorSet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "GetValidatorSet"));
            self.inner.unary(req, path, codec).await
        }
        /// Native-token supply snapshot (minted, burned, circulating).
        pub async fn get_supply(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSupplyRequest>,
        ) -> std::result::Result<tonic::Response<super::Supply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/GetSupply",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "GetSupply"));
            self.inner.unary(req, path, codec).await
        }
        /// Pending-tx count + a capped header window for UI display.
        pub async fn get_mempool(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMempoolRequest>,
        ) -> std::result::Result<tonic::Response<super::Mempool>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/GetMempool",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "GetMempool"));
            self.inner.unary(req, path, codec).await
        }
        /// Server-streaming chain events. Subscribe once, receive every event type
        /// until cancel or server restart. Replaces N separate eth_subscribe calls.
        /// Backpressure: server bounded channel per stream (capacity 4096 — same as
        /// event_tx in chain). On slow client, server drops OLDEST events and emits
        /// a StreamLagged sentinel. Client should resync state from RPC.
        pub async fn stream_events(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ChainEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentrix.v1.Sentrix/StreamEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sentrix.v1.Sentrix", "StreamEvents"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
